path:
  raw_path: "./data/raw/"
  processed_path: "./data/processed/"
  files_path: "./artifacts/files/"

dataloader:
  dataset: "/Users/macbook/Desktop/DNA-Classification/data/raw/DNA-Classification.csv"
  split_size: 0.20
  approaches: ["single", "di"]

model:
  model_name: "RF" # It would be either "RF", "DT", "NB", "LR"
  