path:
  raw_path: "../data/raw/"
  processed_path: "../data/processed/"
  files_path: "../artifacts/files/"

dataloader:
  dataset: "../data/raw/DNA-Classification.csv"
  split_size: 0.20
  approaches: ["single", "di", "gc_content"] # There is another approach named "gc_content"

model:
  model_name: "RF" # It would be either "RF", "DT", "NB", "LR"

  